import type { ShipdeskConfig } from "../types.js";

/**
 * Generate the `electron-builder.yml` configuration for packaging.
 */
export function generateElectronBuilderConfig(config: ShipdeskConfig): string {
  const title = config.name
    .replace(/[-_]/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());

  const lines: string[] = [
    "# Generated by shipdesk",
    `appId: ${config.appId}`,
    `productName: ${title}`,
    "",
    "directories:",
    "  output: ../../.shipdesk/release",
    "",
    "files:",
    "  - main.cjs",
    "",
    "extraResources:",
    '  - from: "server"',
    '    to: "server"',
    "    filter:",
    '      - "**/*"',
    "",
    "npmRebuild: true",
    "",
    "mac:",
    "  category: public.app-category.utilities",
    "  target:",
    "    - dmg",
    "    - zip",
    "",
    "win:",
    "  target:",
    "    - nsis",
    "",
    "linux:",
    "  category: Utility",
    "  target:",
    "    - AppImage",
    "    - deb",
    "",
  ];

  return lines.join("\n");
}
