import type { DeskpackConfig } from "../types.js";

/**
 * Generate the Electron main process file (`main.cjs`).
 */
export function generateElectronMain(config: DeskpackConfig): string {
  const title = toTitleCase(config.name);
  const topology = config.topology;
  const backendHealthPath = normalizeHealthPath(config.backend.healthCheckPath);
  const unsupportedMessage = unsupportedTopologyMessage(topology);

  return `
// Generated by deskpack — do not edit manually
// @ts-check
const { app, BrowserWindow, shell, dialog, utilityProcess } = require("electron");
const path = require("path");
const http = require("http");
const fs = require("fs");
const net = require("net");
const { URL } = require("url");
const { promisify } = require("util");

const sleep = promisify(setTimeout);

const TOPOLOGY = ${JSON.stringify(topology)};
const UNSUPPORTED_TOPOLOGY_MESSAGE = ${JSON.stringify(unsupportedMessage)};
const PREFERRED_API_PORT = ${config.backend.devPort};
const PREFERRED_FRONTEND_PORT = ${config.frontend.devPort};
const BACKEND_HEALTH_PATH = ${JSON.stringify(backendHealthPath)};
const API_PROXY_PREFIXES = ${JSON.stringify(config.backend.apiPrefixes ?? ["/api"])};
const WINDOW_TITLE = ${JSON.stringify(title)};
const WINDOW_WIDTH = ${config.electron.window.width};
const WINDOW_HEIGHT = ${config.electron.window.height};
const isDev = !app.isPackaged;

const gotSingleInstanceLock = app.requestSingleInstanceLock();
if (!gotSingleInstanceLock) {
  app.quit();
  process.exit(0);
}

let mainWindow = null;
let apiProcess = null;
let staticServer = null;
let startupFailed = false;
let startupStarted = false;
let isQuitting = false;
let activeLoadUrl = "";
let backendCrashReason = "";

const MIME_TYPES = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".mjs": "application/javascript; charset=utf-8",
  ".cjs": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".map": "application/json; charset=utf-8",
  ".txt": "text/plain; charset=utf-8",
  ".xml": "application/xml; charset=utf-8",
  ".pdf": "application/pdf",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".avif": "image/avif",
  ".bmp": "image/bmp",
  ".tif": "image/tiff",
  ".tiff": "image/tiff",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".eot": "application/vnd.ms-fontobject",
  ".otf": "font/otf",
  ".wasm": "application/wasm",
  ".mp3": "audio/mpeg",
  ".wav": "audio/wav",
  ".ogg": "audio/ogg",
  ".mp4": "video/mp4",
  ".webm": "video/webm",
};

function logInfo(message) {
  console.log("[deskpack] " + message);
}

function logWarn(message) {
  console.warn("[deskpack] " + message);
}

function uniqueProbePaths(paths) {
  const seen = new Set();
  const result = [];
  for (const pathValue of paths) {
    if (!pathValue) continue;
    const normalized = pathValue.startsWith("/") ? pathValue : "/" + pathValue;
    if (!seen.has(normalized)) {
      seen.add(normalized);
      result.push(normalized);
    }
  }
  return result;
}

function toErrorMessage(error) {
  return error instanceof Error ? error.message : String(error);
}

function showStartupError(message) {
  if (startupFailed) return;
  startupFailed = true;
  console.error("[deskpack] " + message);
  dialog.showErrorBox("Startup Error", message);
  app.quit();
}

async function isPortFree(port) {
  return new Promise((resolve) => {
    const tester = net.createServer();
    tester.unref();
    tester.once("error", () => resolve(false));
    tester.once("listening", () => {
      tester.close(() => resolve(true));
    });
    tester.listen({ host: "127.0.0.1", port });
  });
}

async function allocateFallbackPort() {
  return new Promise((resolve, reject) => {
    const tester = net.createServer();
    tester.unref();
    tester.once("error", reject);
    tester.once("listening", () => {
      const address = tester.address();
      const port = typeof address === "object" && address ? address.port : 0;
      tester.close((closeError) => {
        if (closeError) {
          reject(closeError);
          return;
        }
        if (!port) {
          reject(new Error("Could not allocate a free port."));
          return;
        }
        resolve(port);
      });
    });
    tester.listen({ host: "127.0.0.1", port: 0 });
  });
}

async function resolvePort(preferredPort, label) {
  if (preferredPort > 0 && (await isPortFree(preferredPort))) {
    logInfo("Using " + label + " port " + preferredPort + ".");
    return preferredPort;
  }

  const fallbackPort = await allocateFallbackPort();
  if (preferredPort > 0) {
    logWarn(
      "Preferred " +
        label +
        " port " +
        preferredPort +
        " is unavailable. Falling back to " +
        fallbackPort +
        ".",
    );
  } else {
    logInfo("Using " + label + " port " + fallbackPort + ".");
  }

  return fallbackPort;
}

async function requireConfiguredPort(preferredPort, label) {
  if (preferredPort <= 0) {
    throw new Error("No configured " + label + " port was provided.");
  }

  if (!(await isPortFree(preferredPort))) {
    throw new Error(
      "Configured " +
        label +
        " port " +
        preferredPort +
        " is unavailable. Stop the process using it or update deskpack.config.json.",
    );
  }

  logInfo("Using " + label + " port " + preferredPort + ".");
  return preferredPort;
}

function probeHttp(port, probePath, timeoutMs = 1200) {
  return new Promise((resolve) => {
    const request = http.get(
      {
        hostname: "127.0.0.1",
        port,
        path: probePath,
        timeout: timeoutMs,
      },
      (response) => {
        response.resume();
        resolve({
          ok: Boolean(response.statusCode && response.statusCode < 500),
          statusCode: response.statusCode ?? 0,
        });
      },
    );

    request.on("timeout", () => {
      request.destroy(new Error("timeout"));
    });
    request.on("error", () => resolve({ ok: false, statusCode: 0 }));
  });
}

async function waitForServerReady({
  label,
  port,
  timeoutMs,
  preferredHealthPath,
  extraProbePaths = [],
  crashDetails = () => "",
}) {
  const probePaths = uniqueProbePaths([
    preferredHealthPath,
    "/healthz",
    "/health",
    "/ready",
    ...extraProbePaths,
  ]);

  const startedAt = Date.now();
  while (Date.now() - startedAt <= timeoutMs) {
    const crash = crashDetails();
    if (crash) {
      throw new Error(crash);
    }

    for (const probePath of probePaths) {
      const probe = await probeHttp(port, probePath);
      if (probe.ok) {
        logInfo(
          label +
            " ready on port " +
            port +
            " (probe " +
            probePath +
            ", status " +
            probe.statusCode +
            ").",
        );
        return;
      }
    }

    await sleep(350);
  }

  const crash = crashDetails();
  if (crash) {
    throw new Error(crash);
  }

  throw new Error(
    "Timed out waiting for " +
      label +
      " on port " +
      port +
      ". Tried: " +
      probePaths.join(", "),
  );
}

function resolveStaticPath(staticRoot, requestPath) {
  const normalizedUrlPath = path.posix.normalize(requestPath.replace(/\\\\/g, "/"));
  const relativePath = normalizedUrlPath.startsWith("/")
    ? "." + normalizedUrlPath
    : "./" + normalizedUrlPath;
  const resolvedPath = path.resolve(staticRoot, relativePath);
  const rootWithSep = staticRoot.endsWith(path.sep) ? staticRoot : staticRoot + path.sep;

  if (resolvedPath !== staticRoot && !resolvedPath.startsWith(rootWithSep)) {
    return null;
  }

  return resolvedPath;
}

function sendStaticFile(filePath, response) {
  const extension = path.extname(filePath).toLowerCase();
  const contentType = MIME_TYPES[extension] || "application/octet-stream";

  fs.readFile(filePath, (error, content) => {
    if (error) {
      response.writeHead(500, { "Content-Type": "text/plain; charset=utf-8" });
      response.end("Server error");
      return;
    }
    response.writeHead(200, { "Content-Type": contentType });
    response.end(content);
  });
}

function serveStaticRequest(staticRoot, request, response) {
  let pathname = "/";
  try {
    pathname = new URL(request.url || "/", "http://127.0.0.1").pathname;
    pathname = decodeURIComponent(pathname);
  } catch {
    response.writeHead(400, { "Content-Type": "text/plain; charset=utf-8" });
    response.end("Bad request");
    return;
  }

  const entryFile = path.join(staticRoot, "index.html");
  const requestedPath = pathname === "/" ? "/index.html" : pathname;
  const resolved = resolveStaticPath(staticRoot, requestedPath);
  if (!resolved) {
    response.writeHead(403, { "Content-Type": "text/plain; charset=utf-8" });
    response.end("Forbidden");
    return;
  }

  let candidate = resolved;
  if (fs.existsSync(candidate)) {
    const stat = fs.statSync(candidate);
    if (stat.isDirectory()) {
      candidate = path.join(candidate, "index.html");
    }
  }

  if (fs.existsSync(candidate) && fs.statSync(candidate).isFile()) {
    sendStaticFile(candidate, response);
    return;
  }

  if (!path.extname(pathname) && fs.existsSync(entryFile)) {
    sendStaticFile(entryFile, response);
    return;
  }

  response.writeHead(404, { "Content-Type": "text/plain; charset=utf-8" });
  response.end("Not found");
}

function proxyApiRequest(request, response, backendPort) {
  const options = {
    hostname: "127.0.0.1",
    port: backendPort,
    path: request.url,
    method: request.method,
    headers: { ...request.headers, "X-Forwarded-For": "127.0.0.1" },
  };

  const proxyRequest = http.request(options, (proxyResponse) => {
    if (!proxyResponse.statusCode) {
      response.writeHead(502, { "Content-Type": "text/plain; charset=utf-8" });
      response.end("Bad Gateway");
      return;
    }
    response.writeHead(proxyResponse.statusCode, proxyResponse.headers);
    proxyResponse.pipe(response);
  });

  proxyRequest.on("error", (error) => {
    if (!response.headersSent) {
      response.writeHead(502, { "Content-Type": "text/plain; charset=utf-8" });
      response.end("Proxy error: " + error.message);
    }
  });

  request.pipe(proxyRequest);
}

async function startStaticServer(preferredPort, backendPort) {
  const staticRoot = path.join(process.resourcesPath, "server", "web-dist");
  const entryFile = path.join(staticRoot, "index.html");
  if (!fs.existsSync(entryFile)) {
    throw new Error("Frontend build output missing: " + entryFile);
  }

  const port = await resolvePort(preferredPort, "frontend");
  await new Promise((resolve, reject) => {
    staticServer = http.createServer((request, response) => {
      if (backendPort > 0) {
        let pathname = "/";
        try {
          pathname = new URL(request.url || "/", "http://127.0.0.1").pathname;
        } catch {}

        if (API_PROXY_PREFIXES.some((prefix) => pathname.startsWith(prefix))) {
          proxyApiRequest(request, response, backendPort);
          return;
        }
      }

      serveStaticRequest(staticRoot, request, response);
    });

    staticServer.once("error", reject);
    staticServer.listen(port, "127.0.0.1", () => resolve());
  });

  logInfo("Static frontend server running on port " + port + ".");
  return port;
}

async function startBundledBackend(preferredPort) {
  const backendPort = await requireConfiguredPort(preferredPort, "backend");
  const serverPath = path.join(process.resourcesPath, "server", "server.mjs");
  if (!fs.existsSync(serverPath)) {
    throw new Error("Backend bundle missing: " + serverPath);
  }

  let stderrBuffer = "";
  backendCrashReason = "";

  apiProcess = utilityProcess.fork(serverPath, [], {
    env: {
      ...process.env,
      PORT: String(backendPort),
      DESKPACK_BACKEND_PORT: String(backendPort),
      NODE_ENV: "production",
    },
    cwd: path.dirname(serverPath),
    stdio: "pipe",
    serviceName: "deskpack-backend",
  });

  apiProcess.stdout?.on("data", (chunk) => {
    const message = String(chunk).trim();
    if (message) console.log("[backend] " + message);
  });
  apiProcess.stderr?.on("data", (chunk) => {
    const message = String(chunk);
    stderrBuffer += message;
    const trimmed = message.trim();
    if (trimmed) console.error("[backend:err] " + trimmed);
  });
  apiProcess.once("exit", (code) => {
    const detail = stderrBuffer.trim();
    backendCrashReason =
      "Backend process exited before readiness (code " +
      code +
      ")." +
      (detail ? "\\n\\n" + detail : "");
    if (!isQuitting && !startupFailed && code !== 0) {
      showStartupError(backendCrashReason);
    }
    apiProcess = null;
  });

  await waitForServerReady({
    label: "Backend",
    port: backendPort,
    timeoutMs: 30000,
    preferredHealthPath: BACKEND_HEALTH_PATH,
    extraProbePaths: ["/", "/index.html"],
    crashDetails: () => backendCrashReason,
  });

  return backendPort;
}

function createWindow(url) {
  if (mainWindow) {
    if (mainWindow.isMinimized()) mainWindow.restore();
    mainWindow.focus();
    return;
  }

  activeLoadUrl = url;
  mainWindow = new BrowserWindow({
    width: WINDOW_WIDTH,
    height: WINDOW_HEIGHT,
    minWidth: 800,
    minHeight: 600,
    title: WINDOW_TITLE,
    titleBarStyle: process.platform === "darwin" ? "hiddenInset" : "default",
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  mainWindow.loadURL(url).catch((error) => {
    showStartupError("Failed to load application URL.\\n\\n" + toErrorMessage(error));
  });
  mainWindow.webContents.setWindowOpenHandler(({ url: targetUrl }) => {
    shell.openExternal(targetUrl);
    return { action: "deny" };
  });

  if (isDev) {
    mainWindow.webContents.openDevTools({ mode: "detach" });
  }

  mainWindow.on("closed", () => {
    mainWindow = null;
  });
}

function assertSupportedTopology() {
  if (UNSUPPORTED_TOPOLOGY_MESSAGE) {
    throw new Error(UNSUPPORTED_TOPOLOGY_MESSAGE);
  }
}

async function resolveLoadUrl() {
  if (TOPOLOGY === "backend-serves-frontend") {
    if (isDev) {
      await waitForServerReady({
        label: "Frontend dev server",
        port: PREFERRED_FRONTEND_PORT,
        timeoutMs: 30000,
        preferredHealthPath: "/",
      });
      return "http://127.0.0.1:" + PREFERRED_FRONTEND_PORT;
    }

    const backendPort = await startBundledBackend(PREFERRED_API_PORT);
    return "http://127.0.0.1:" + backendPort;
  }

  if (TOPOLOGY === "frontend-static-separate") {
    if (isDev) {
      await waitForServerReady({
        label: "Frontend dev server",
        port: PREFERRED_FRONTEND_PORT,
        timeoutMs: 30000,
        preferredHealthPath: "/",
      });
      return "http://127.0.0.1:" + PREFERRED_FRONTEND_PORT;
    }

    const backendPort = await startBundledBackend(PREFERRED_API_PORT);
    const frontendPort = await startStaticServer(PREFERRED_FRONTEND_PORT, backendPort);
    return "http://127.0.0.1:" + frontendPort;
  }

  if (TOPOLOGY === "frontend-only-static") {
    if (isDev) {
      await waitForServerReady({
        label: "Frontend dev server",
        port: PREFERRED_FRONTEND_PORT,
        timeoutMs: 30000,
        preferredHealthPath: "/",
      });
      return "http://127.0.0.1:" + PREFERRED_FRONTEND_PORT;
    }

    const frontendPort = await startStaticServer(PREFERRED_FRONTEND_PORT, 0);
    return "http://127.0.0.1:" + frontendPort;
  }

  throw new Error("Unsupported topology: " + TOPOLOGY);
}

app.on("second-instance", () => {
  if (!mainWindow) return;
  if (mainWindow.isMinimized()) mainWindow.restore();
  mainWindow.focus();
});

app.whenReady().then(async () => {
  if (startupStarted) return;
  startupStarted = true;

  try {
    assertSupportedTopology();
    const loadUrl = await resolveLoadUrl();
    createWindow(loadUrl);
  } catch (error) {
    showStartupError("Failed to start the application.\\n\\n" + toErrorMessage(error));
  }

  app.on("activate", () => {
    if (startupFailed || !activeLoadUrl) return;
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow(activeLoadUrl);
    }
  });
});

app.on("before-quit", () => {
  isQuitting = true;

  if (apiProcess) {
    apiProcess.kill();
    apiProcess = null;
  }
  if (staticServer) {
    staticServer.close();
    staticServer = null;
  }
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});
`.trimStart();
}

function toTitleCase(value: string): string {
  return value
    .replace(/[-_]/g, " ")
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

function normalizeHealthPath(value: string | undefined): string {
  if (!value || value.trim().length === 0) {
    return "/";
  }
  return value.startsWith("/") ? value : `/${value}`;
}

function unsupportedTopologyMessage(topology: DeskpackConfig["topology"]): string | null {
  if (topology === "ssr-framework") {
    return (
      "Next.js SSR/server runtime projects are not supported yet. " +
      "Use a static export (output: 'export') and re-run deskpack init."
    );
  }

  if (topology === "unsupported") {
    return (
      "Deskpack could not determine a supported frontend/backend topology. " +
      "Ensure your backend serves static frontend files or that your frontend can be built as static output."
    );
  }

  return null;
}
