import type { DeskpackConfig } from "../types.js";

/**
 * Generate the Electron main process file (`main.cjs`).
 */
export function generateElectronMain(config: DeskpackConfig): string {
  const title = toTitleCase(config.name);
  const topology = config.topology;
  const backendHealthPath = normalizeHealthPath(config.backend.healthCheckPath);
  const unsupportedMessage = unsupportedTopologyMessage(topology);

  return `
// Generated by deskpack — do not edit manually
// @ts-check
const { app, BrowserWindow, shell, dialog, utilityProcess, session } = require("electron");
const path = require("path");
const http = require("http");
const fs = require("fs");
const net = require("net");
const { URL } = require("url");
const { promisify } = require("util");

const sleep = promisify(setTimeout);

const TOPOLOGY = ${JSON.stringify(topology)};
const UNSUPPORTED_TOPOLOGY_MESSAGE = ${JSON.stringify(unsupportedMessage)};
const PREFERRED_API_PORT = ${config.backend.devPort};
const PREFERRED_FRONTEND_PORT = ${config.frontend.devPort};
const BACKEND_HEALTH_PATH = ${JSON.stringify(backendHealthPath)};
const API_PROXY_PREFIXES = ${JSON.stringify(config.backend.apiPrefixes ?? ["/api"])};
const PROXY_REWRITE = ${JSON.stringify(config.backend.proxyRewrite ?? null)};
const DATABASE_CONFIG = ${JSON.stringify(config.database ?? null)};
const BACKEND_PROXY_PREFIX = "/__deskpack_backend__";
const WINDOW_TITLE = ${JSON.stringify(title)};
const WINDOW_WIDTH = ${config.electron.window.width};
const WINDOW_HEIGHT = ${config.electron.window.height};
const isDev = !app.isPackaged;

const gotSingleInstanceLock = app.requestSingleInstanceLock();
if (!gotSingleInstanceLock) {
  app.quit();
  process.exit(0);
}

let mainWindow = null;
let apiProcess = null;
let staticServer = null;
let startupFailed = false;
let startupStarted = false;
let isQuitting = false;
let activeLoadUrl = "";
let activeRendererOrigin = "";
let backendCrashReason = "";

const MIME_TYPES = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".mjs": "application/javascript; charset=utf-8",
  ".cjs": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".map": "application/json; charset=utf-8",
  ".txt": "text/plain; charset=utf-8",
  ".xml": "application/xml; charset=utf-8",
  ".pdf": "application/pdf",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".avif": "image/avif",
  ".bmp": "image/bmp",
  ".tif": "image/tiff",
  ".tiff": "image/tiff",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".eot": "application/vnd.ms-fontobject",
  ".otf": "font/otf",
  ".wasm": "application/wasm",
  ".mp3": "audio/mpeg",
  ".wav": "audio/wav",
  ".ogg": "audio/ogg",
  ".mp4": "video/mp4",
  ".webm": "video/webm",
};

const STATIC_HTML_CSP = [
  "default-src 'self'",
  "base-uri 'self'",
  "frame-ancestors 'none'",
  "object-src 'none'",
  "script-src 'self' 'unsafe-inline'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  "font-src 'self' data:",
  "connect-src 'self' https: http://127.0.0.1:* http://localhost:*",
].join("; ");

function logInfo(message) {
  console.log("[deskpack] " + message);
}

function logWarn(message) {
  console.warn("[deskpack] " + message);
}

function parseUrl(rawUrl) {
  try {
    return new URL(rawUrl);
  } catch {
    return null;
  }
}

function isLoopbackHostname(hostname) {
  return hostname === "127.0.0.1" || hostname === "localhost";
}

function originFromUrl(rawUrl) {
  const parsed = parseUrl(rawUrl);
  return parsed ? parsed.origin : "";
}

function isAllowedNavigationUrl(rawUrl) {
  const parsed = parseUrl(rawUrl);
  if (!parsed) return false;
  if (parsed.protocol !== "http:") return false;
  if (!isLoopbackHostname(parsed.hostname)) return false;
  return parsed.origin === activeRendererOrigin;
}

function isAllowedExternalUrl(rawUrl) {
  const parsed = parseUrl(rawUrl);
  if (!parsed) return false;
  return parsed.protocol === "https:" || parsed.protocol === "mailto:";
}

function parseLoopbackOrigin(rawValue) {
  if (!rawValue || typeof rawValue !== "string") return "";
  const parsed = parseUrl(rawValue);
  if (!parsed || parsed.protocol !== "http:") return "";
  if (!isLoopbackHostname(parsed.hostname)) return "";
  return parsed.origin;
}

function mergeVaryHeader(existing, value) {
  const current = Array.isArray(existing) ? existing.join(", ") : (existing || "");
  const values = current
    .split(",")
    .map((entry) => entry.trim())
    .filter(Boolean);

  if (!values.some((entry) => entry.toLowerCase() === value.toLowerCase())) {
    values.push(value);
  }

  return [values.join(", ")];
}

function findHeaderName(headers, targetName) {
  const lowerTarget = targetName.toLowerCase();
  return Object.keys(headers).find((name) => name.toLowerCase() === lowerTarget) || null;
}

function setHeaderValue(headers, name, value) {
  const existingName = findHeaderName(headers, name);
  if (existingName && existingName !== name) {
    delete headers[existingName];
  }
  headers[name] = value;
}

function uniqueProbePaths(paths) {
  const seen = new Set();
  const result = [];
  for (const pathValue of paths) {
    if (!pathValue) continue;
    const normalized = pathValue.startsWith("/") ? pathValue : "/" + pathValue;
    if (!seen.has(normalized)) {
      seen.add(normalized);
      result.push(normalized);
    }
  }
  return result;
}

function toErrorMessage(error) {
  if (!(error instanceof Error)) return String(error);
  var msg = error.message;
  var code = error.code;
  if (
    code === "EADDRINUSE" ||
    /\\bEADDRINUSE\\b/i.test(msg) ||
    /address already in use/i.test(msg) ||
    (/is unavailable/i.test(msg) && /\\bport\\b/i.test(msg) && /\\d{2,5}/.test(msg))
  ) {
    var port = undefined;
    var match =
      msg.match(/127\\.0\\.0\\.1:(\\d+)/) ||
      msg.match(/localhost:(\\d+)/) ||
      msg.match(/:(\\d+)\\s*$/m) ||
      msg.match(/\\bport\\s+(\\d+)/i);
    if (match) port = parseInt(match[1], 10);
    var intro =
      port > 0 && port <= 65535
        ? "Something else is already listening on port " + port + ".\\n\\n"
        : "Something else is already using that network port.\\n\\n";
    return (
      intro +
      "Usually that is another dev server or a previous process that did not exit. Stop it " +
      "(or quit the app using it), or change the dev port in deskpack.config.json and try again."
    );
  }
  if (error.cause instanceof Error) {
    var inner = toErrorMessage(error.cause);
    if (inner !== error.cause.message) return inner;
  }
  return msg;
}

function formatNativeCrashDetail(detail) {
  if (
    process.platform === "win32" &&
    /ERR_DLOPEN_FAILED|\\.node|The specified module could not be found/i.test(detail) &&
    /@libsql|libsql|win32-x64-msvc|VCRUNTIME|MSVCP/i.test(detail)
  ) {
    return (
      "This app requires the Microsoft Visual C++ Redistributable 2015-2022 x64 to run its native database dependency.\\n\\n" +
      "Install it from https://aka.ms/vc14/vc_redist.x64.exe, then restart the app.\\n\\n" +
      "Original error:\\n" +
      detail
    );
  }

  return detail;
}

function showStartupError(message) {
  if (startupFailed) return;
  startupFailed = true;
  console.error("[deskpack] " + message);
  dialog.showErrorBox("Startup Error", message);
  app.quit();
}

function readSqliteSchemaText(filePath) {
  if (!fs.existsSync(filePath)) return "";
  try {
    return fs.readFileSync(filePath).toString("utf8");
  } catch {
    return "";
  }
}

function sqliteFileHasUserTables(filePath) {
  const content = [
    readSqliteSchemaText(filePath),
    readSqliteSchemaText(filePath + "-wal"),
  ].join("\\n");
  const tablePattern = new RegExp(
    "CREATE\\\\s+(?:VIRTUAL\\\\s+)?TABLE\\\\s+(?:IF\\\\s+NOT\\\\s+EXISTS\\\\s+)?[\\\\x60\\\"\\\\[]?([^\\\\x60\\\"\\\\]\\\\s(]+)",
    "gi",
  );
  for (const match of content.matchAll(tablePattern)) {
    const tableName = String(match[1] || "").toLowerCase();
    if (
      tableName &&
      !tableName.startsWith("sqlite_") &&
      tableName !== "__drizzle_migrations" &&
      tableName !== "_prisma_migrations"
    ) {
      return true;
    }
  }
  return false;
}

function removeSqliteSidecars(filePath) {
  for (const suffix of ["-wal", "-shm", "-journal"]) {
    try {
      fs.rmSync(filePath + suffix, { force: true });
    } catch {
      // Best effort cleanup before replacing an uninitialized database.
    }
  }
}

function prepareManagedSqliteDatabase() {
  if (!DATABASE_CONFIG || DATABASE_CONFIG.provider !== "sqlite") return {};

  const databaseDir = path.join(app.getPath("userData"), DATABASE_CONFIG.userDataSubdir);
  fs.mkdirSync(databaseDir, { recursive: true });

  const runtimePath = path.join(databaseDir, DATABASE_CONFIG.runtimeFileName);
  const templatePath = path.join(process.resourcesPath, "server", "database", "template.db");
  if (!fs.existsSync(runtimePath) && fs.existsSync(templatePath)) {
    fs.copyFileSync(templatePath, runtimePath);
    logInfo("Created SQLite database at " + runtimePath + ".");
  } else if (
    fs.existsSync(runtimePath) &&
    fs.existsSync(templatePath) &&
    !sqliteFileHasUserTables(runtimePath) &&
    sqliteFileHasUserTables(templatePath)
  ) {
    removeSqliteSidecars(runtimePath);
    fs.copyFileSync(templatePath, runtimePath);
    logInfo("Repaired uninitialized SQLite database at " + runtimePath + ".");
  }

  return {
    [DATABASE_CONFIG.env.pathVar]: runtimePath,
    [DATABASE_CONFIG.env.urlVar]: "file:" + runtimePath,
  };
}

function managedSqliteExecArgv() {
  const preloadPath = path.join(process.resourcesPath, "server", "database", "sqlite-preload.cjs");
  return fs.existsSync(preloadPath) ? ["--require", preloadPath] : [];
}

function preparePlaywrightBrowsersEnv() {
  const browsersPath = path.join(process.resourcesPath, "server", "ms-playwright");
  return fs.existsSync(browsersPath) ? { PLAYWRIGHT_BROWSERS_PATH: browsersPath } : {};
}

function serverRuntimeEnv(extra) {
  return {
    ...process.env,
    ...prepareManagedSqliteDatabase(),
    ...preparePlaywrightBrowsersEnv(),
    ...extra,
  };
}

async function isPortFree(port) {
  return new Promise((resolve) => {
    const tester = net.createServer();
    tester.unref();
    tester.once("error", () => resolve(false));
    tester.once("listening", () => {
      tester.close(() => resolve(true));
    });
    tester.listen({ host: "127.0.0.1", port });
  });
}

async function allocateFallbackPort() {
  return new Promise((resolve, reject) => {
    const tester = net.createServer();
    tester.unref();
    tester.once("error", reject);
    tester.once("listening", () => {
      const address = tester.address();
      const port = typeof address === "object" && address ? address.port : 0;
      tester.close((closeError) => {
        if (closeError) {
          reject(closeError);
          return;
        }
        if (!port) {
          reject(new Error("Could not allocate a free port."));
          return;
        }
        resolve(port);
      });
    });
    tester.listen({ host: "127.0.0.1", port: 0 });
  });
}

async function resolvePort(preferredPort, label) {
  if (preferredPort > 0 && (await isPortFree(preferredPort))) {
    logInfo("Using " + label + " port " + preferredPort + ".");
    return preferredPort;
  }

  const fallbackPort = await allocateFallbackPort();
  if (preferredPort > 0) {
    logWarn(
      "Preferred " +
        label +
        " port " +
        preferredPort +
        " is unavailable. Falling back to " +
        fallbackPort +
        ".",
    );
  } else {
    logInfo("Using " + label + " port " + fallbackPort + ".");
  }

  return fallbackPort;
}

async function requireConfiguredPort(preferredPort, label) {
  if (preferredPort <= 0) {
    throw new Error("No configured " + label + " port was provided.");
  }

  if (!(await isPortFree(preferredPort))) {
    throw new Error(
      "Configured " +
        label +
        " port " +
        preferredPort +
        " is unavailable. Stop the process using it or update deskpack.config.json.",
    );
  }

  logInfo("Using " + label + " port " + preferredPort + ".");
  return preferredPort;
}

function probeHttp(port, probePath, timeoutMs = 1200) {
  return new Promise((resolve) => {
    const request = http.get(
      {
        hostname: "127.0.0.1",
        port,
        path: probePath,
        timeout: timeoutMs,
      },
      (response) => {
        response.resume();
        resolve({
          ok: Boolean(response.statusCode && response.statusCode < 500),
          statusCode: response.statusCode ?? 0,
        });
      },
    );

    request.on("timeout", () => {
      request.destroy(new Error("timeout"));
    });
    request.on("error", () => resolve({ ok: false, statusCode: 0 }));
  });
}

async function waitForServerReady({
  label,
  port,
  timeoutMs,
  preferredHealthPath,
  extraProbePaths = [],
  crashDetails = () => "",
}) {
  const probePaths = uniqueProbePaths([
    preferredHealthPath,
    "/healthz",
    "/health",
    "/ready",
    ...extraProbePaths,
  ]);

  const startedAt = Date.now();
  while (Date.now() - startedAt <= timeoutMs) {
    const crash = crashDetails();
    if (crash) {
      throw new Error(crash);
    }

    for (const probePath of probePaths) {
      const probe = await probeHttp(port, probePath);
      if (probe.ok) {
        logInfo(
          label +
            " ready on port " +
            port +
            " (probe " +
            probePath +
            ", status " +
            probe.statusCode +
            ").",
        );
        return;
      }
    }

    await sleep(350);
  }

  const crash = crashDetails();
  if (crash) {
    throw new Error(crash);
  }

  throw new Error(
    "Timed out waiting for " +
      label +
      " on port " +
      port +
      ". Tried: " +
      probePaths.join(", "),
  );
}

async function ensureBackendServesFrontend(port, timeoutMs = 5000) {
  const probePaths = ["/", "/index.html"];
  const startedAt = Date.now();

  while (Date.now() - startedAt <= timeoutMs) {
    for (const probePath of probePaths) {
      const probe = await probeHttp(port, probePath);
      if (probe.statusCode >= 200 && probe.statusCode < 400) {
        logInfo(
          "Backend frontend route ready on port " +
            port +
            " (probe " +
            probePath +
            ", status " +
            probe.statusCode +
            ").",
        );
        return;
      }
    }

    await sleep(250);
  }

  throw new Error(
    "Backend started on port " +
      port +
      " but did not serve frontend routes. Tried: " +
      probePaths.join(", "),
  );
}

function resolveStaticPath(staticRoot, requestPath) {
  const normalizedUrlPath = path.posix.normalize(requestPath.replace(/\\\\/g, "/"));
  const relativePath = normalizedUrlPath.startsWith("/")
    ? "." + normalizedUrlPath
    : "./" + normalizedUrlPath;
  const resolvedPath = path.resolve(staticRoot, relativePath);
  const rootWithSep = staticRoot.endsWith(path.sep) ? staticRoot : staticRoot + path.sep;

  if (resolvedPath !== staticRoot && !resolvedPath.startsWith(rootWithSep)) {
    return null;
  }

  return resolvedPath;
}

function sendStaticFile(filePath, response) {
  const extension = path.extname(filePath).toLowerCase();
  const contentType = MIME_TYPES[extension] || "application/octet-stream";

  fs.readFile(filePath, (error, content) => {
    if (error) {
      response.writeHead(500, { "Content-Type": "text/plain; charset=utf-8" });
      response.end("Server error");
      return;
    }

    const headers = {
      "Content-Type": contentType,
      "X-Content-Type-Options": "nosniff",
    };

    if (extension === ".html") {
      headers["Content-Security-Policy"] = STATIC_HTML_CSP;
    }

    response.writeHead(200, headers);
    response.end(content);
  });
}

function resolvePackagedHtmlEntry(staticRoot) {
  const indexFile = path.join(staticRoot, "index.html");
  const shellFile = path.join(staticRoot, "_shell.html");
  if (fs.existsSync(indexFile)) return indexFile;
  if (fs.existsSync(shellFile)) return shellFile;
  return null;
}

function hasAnyHtmlUnder(dir, depth) {
  if (depth > 8) return false;
  let entries;
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return false;
  }
  for (const entry of entries) {
    if (entry.name.startsWith(".")) continue;
    if (entry.name === "node_modules") continue;
    const full = path.join(dir, entry.name);
    if (entry.isFile() && entry.name.endsWith(".html")) return true;
    if (entry.isDirectory() && hasAnyHtmlUnder(full, depth + 1)) return true;
  }
  return false;
}

function serveStaticRequest(staticRoot, request, response) {
  let pathname = "/";
  try {
    pathname = new URL(request.url || "/", "http://127.0.0.1").pathname;
    pathname = decodeURIComponent(pathname);
  } catch {
    response.writeHead(400, { "Content-Type": "text/plain; charset=utf-8" });
    response.end("Bad request");
    return;
  }

  const packagedEntry = resolvePackagedHtmlEntry(staticRoot);
  const requestedPath = pathname === "/" ? "/index.html" : pathname;
  const resolved = resolveStaticPath(staticRoot, requestedPath);
  if (!resolved) {
    response.writeHead(403, { "Content-Type": "text/plain; charset=utf-8" });
    response.end("Forbidden");
    return;
  }

  let candidate = resolved;
  if (fs.existsSync(candidate)) {
    const stat = fs.statSync(candidate);
    if (stat.isDirectory()) {
      candidate = path.join(candidate, "index.html");
    }
  }

  if (fs.existsSync(candidate) && fs.statSync(candidate).isFile()) {
    sendStaticFile(candidate, response);
    return;
  }

  if (!path.extname(pathname) && packagedEntry && fs.existsSync(packagedEntry)) {
    sendStaticFile(packagedEntry, response);
    return;
  }

  response.writeHead(404, { "Content-Type": "text/plain; charset=utf-8" });
  response.end("Not found");
}

function applyProxyRewrite(urlPath) {
  if (!PROXY_REWRITE || !urlPath) return urlPath;
  if (urlPath.startsWith(PROXY_REWRITE)) {
    return urlPath.slice(PROXY_REWRITE.length) || "/";
  }
  return urlPath;
}

function stripBackendProxyPrefix(urlPath) {
  if (!urlPath.startsWith(BACKEND_PROXY_PREFIX)) return urlPath;
  const stripped = urlPath.slice(BACKEND_PROXY_PREFIX.length);
  if (!stripped) return "/";
  return stripped.startsWith("/") ? stripped : "/" + stripped;
}

function proxyApiRequest(request, response, backendPort) {
  const proxiedPath = applyProxyRewrite(request.url);
  proxyBackendRequest(request, response, backendPort, proxiedPath);
}

function proxyAbsoluteBackendRequest(request, response, backendPort) {
  const proxiedPath = stripBackendProxyPrefix(request.url);
  proxyBackendRequest(request, response, backendPort, proxiedPath);
}

function withRendererCorsHeaders(headers) {
  const nextHeaders = { ...headers };
  if (!activeRendererOrigin) return nextHeaders;

  setHeaderValue(nextHeaders, "access-control-allow-origin", [activeRendererOrigin]);
  setHeaderValue(nextHeaders, "vary", mergeVaryHeader(nextHeaders["vary"], "Origin"));
  setHeaderValue(
    nextHeaders,
    "access-control-allow-methods",
    ["GET, POST, PUT, DELETE, PATCH, OPTIONS"],
  );
  setHeaderValue(nextHeaders, "access-control-allow-headers", [
    "Content-Type, Authorization, X-Requested-With, Accept, trpc-accept, x-trpc-source",
  ]);

  return nextHeaders;
}

function proxyBackendRequest(request, response, backendPort, proxiedPath) {
  const forwardedHeaders = { ...request.headers };
  delete forwardedHeaders.host;
  delete forwardedHeaders.connection;
  delete forwardedHeaders["keep-alive"];
  delete forwardedHeaders["proxy-connection"];
  delete forwardedHeaders["transfer-encoding"];
  delete forwardedHeaders.upgrade;
  delete forwardedHeaders["content-length"];

  const options = {
    hostname: "127.0.0.1",
    port: backendPort,
    path: proxiedPath,
    method: request.method,
    headers: {
      ...forwardedHeaders,
      host: "127.0.0.1:" + backendPort,
      "X-Forwarded-For": "127.0.0.1",
    },
  };

  const proxyRequest = http.request(options, (proxyResponse) => {
    if (!proxyResponse.statusCode) {
      response.writeHead(502, { "Content-Type": "text/plain; charset=utf-8" });
      response.end("Bad Gateway");
      return;
    }
    response.writeHead(proxyResponse.statusCode, withRendererCorsHeaders(proxyResponse.headers));
    proxyResponse.pipe(response);
  });

  proxyRequest.on("error", (error) => {
    if (!response.headersSent) {
      response.writeHead(502, { "Content-Type": "text/plain; charset=utf-8" });
      response.end("Proxy error: " + error.message);
    }
  });

  request.pipe(proxyRequest);
}

async function startStaticServer(preferredPort, backendPort) {
  const staticRoot = path.join(process.resourcesPath, "server", "web-dist");
  const packagedEntry = resolvePackagedHtmlEntry(staticRoot);
  if (!packagedEntry && !hasAnyHtmlUnder(staticRoot, 0)) {
    throw new Error(
      "Frontend build output missing static HTML (expected index.html, _shell.html, or prerendered *.html) under " +
        staticRoot,
    );
  }

  const port = await resolvePort(preferredPort, "frontend");
  await new Promise((resolve, reject) => {
    staticServer = http.createServer((request, response) => {
      if (backendPort > 0) {
        let pathname = "/";
        try {
          pathname = new URL(request.url || "/", "http://127.0.0.1").pathname;
        } catch {}

        if (API_PROXY_PREFIXES.some((prefix) => pathname.startsWith(prefix))) {
          proxyApiRequest(request, response, backendPort);
          return;
        }

        if (pathname.startsWith(BACKEND_PROXY_PREFIX)) {
          proxyAbsoluteBackendRequest(request, response, backendPort);
          return;
        }
      }

      serveStaticRequest(staticRoot, request, response);
    });

    staticServer.once("error", reject);
    staticServer.listen(port, "127.0.0.1", () => resolve());
  });

  logInfo("Static frontend server running on port " + port + ".");
  return port;
}

async function startBundledBackend(preferredPort) {
  const backendPort = await requireConfiguredPort(preferredPort, "backend");
  const serverPath = path.join(process.resourcesPath, "server", "server.mjs");
  if (!fs.existsSync(serverPath)) {
    throw new Error("Backend bundle missing: " + serverPath);
  }

  let stderrBuffer = "";
  backendCrashReason = "";

  apiProcess = utilityProcess.fork(serverPath, [], {
    env: serverRuntimeEnv({
      PORT: String(backendPort),
      DESKPACK_BACKEND_PORT: String(backendPort),
      NODE_ENV: "production",
    }),
    execArgv: managedSqliteExecArgv(),
    cwd: path.dirname(serverPath),
    stdio: "pipe",
    serviceName: "deskpack-backend",
  });

  apiProcess.stdout?.on("data", (chunk) => {
    const message = String(chunk).trim();
    if (message) console.log("[backend] " + message);
  });
  apiProcess.stderr?.on("data", (chunk) => {
    const message = String(chunk);
    stderrBuffer += message;
    const trimmed = message.trim();
    if (trimmed) console.error("[backend:err] " + trimmed);
  });
  apiProcess.once("exit", (code) => {
    const detail = formatNativeCrashDetail(stderrBuffer.trim());
    backendCrashReason =
      "Backend process exited before readiness (code " +
      code +
      ")." +
      (detail ? "\\n\\n" + detail : "");
    if (!isQuitting && !startupFailed && code !== 0) {
      showStartupError(backendCrashReason);
    }
    apiProcess = null;
  });

  await waitForServerReady({
    label: "Backend",
    port: backendPort,
    timeoutMs: 30000,
    preferredHealthPath: BACKEND_HEALTH_PATH,
    extraProbePaths: ["/", "/index.html"],
    crashDetails: () => backendCrashReason,
  });

  return backendPort;
}

async function startNextStandaloneServer(preferredPort) {
  const nextPort = await resolvePort(preferredPort, "Next.js");
  const nextDir = path.join(process.resourcesPath, "server", "next");
  const launcherPath = path.join(nextDir, "deskpack-next-launcher.cjs");
  const serverPath = fs.existsSync(launcherPath)
    ? launcherPath
    : path.join(nextDir, "server.js");
  if (!fs.existsSync(serverPath)) {
    throw new Error("Next.js standalone server missing: " + path.join(nextDir, "server.js"));
  }

  let stderrBuffer = "";
  backendCrashReason = "";

  apiProcess = utilityProcess.fork(serverPath, [], {
    env: serverRuntimeEnv({
      PORT: String(nextPort),
      HOSTNAME: "127.0.0.1",
      NODE_ENV: "production",
    }),
    execArgv: managedSqliteExecArgv(),
    cwd: nextDir,
    stdio: "pipe",
    serviceName: "deskpack-next",
  });

  apiProcess.stdout?.on("data", (chunk) => {
    const message = String(chunk).trim();
    if (message) console.log("[next] " + message);
  });
  apiProcess.stderr?.on("data", (chunk) => {
    const message = String(chunk);
    stderrBuffer += message;
    const trimmed = message.trim();
    if (trimmed) console.error("[next:err] " + trimmed);
  });
  apiProcess.once("exit", (code) => {
    const detail = formatNativeCrashDetail(stderrBuffer.trim());
    backendCrashReason =
      "Next.js server exited before readiness (code " +
      code +
      ")." +
      (detail ? "\\n\\n" + detail : "");
    if (!isQuitting && !startupFailed && code !== 0) {
      showStartupError(backendCrashReason);
    }
    apiProcess = null;
  });

  await waitForServerReady({
    label: "Next.js",
    port: nextPort,
    timeoutMs: 30000,
    preferredHealthPath: "/",
    crashDetails: () => backendCrashReason,
  });

  return nextPort;
}

function createWindow(url) {
  if (mainWindow) {
    if (mainWindow.isMinimized()) mainWindow.restore();
    mainWindow.focus();
    return;
  }

  activeLoadUrl = url;
  activeRendererOrigin = originFromUrl(url);
  if (!activeRendererOrigin) {
    throw new Error("Could not determine renderer origin from startup URL.");
  }

  mainWindow = new BrowserWindow({
    width: WINDOW_WIDTH,
    height: WINDOW_HEIGHT,
    minWidth: 800,
    minHeight: 600,
    title: WINDOW_TITLE,
    show: false,
    titleBarStyle: process.platform === "darwin" ? "hiddenInset" : "default",
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      sandbox: true,
      webSecurity: true,
    },
  });

  mainWindow.once("ready-to-show", () => {
    mainWindow.show();
    mainWindow.focus();
    if (process.platform === "darwin" && typeof app.focus === "function") {
      try {
        app.focus({ steal: true });
      } catch (_error) {
        // ignore
      }
    }
  });

  mainWindow.loadURL(url).catch((error) => {
    showStartupError("Failed to load application URL.\\n\\n" + toErrorMessage(error));
  });

  mainWindow.webContents.on("will-navigate", (event, targetUrl) => {
    if (isAllowedNavigationUrl(targetUrl)) return;
    event.preventDefault();
    logWarn("Blocked navigation to disallowed URL: " + targetUrl);
  });

  mainWindow.webContents.on("will-redirect", (event, targetUrl) => {
    if (isAllowedNavigationUrl(targetUrl)) return;
    event.preventDefault();
    logWarn("Blocked redirect to disallowed URL: " + targetUrl);
  });

  mainWindow.webContents.setWindowOpenHandler(({ url: targetUrl }) => {
    if (!isAllowedExternalUrl(targetUrl)) {
      logWarn("Blocked external URL: " + targetUrl);
      return { action: "deny" };
    }
    shell.openExternal(targetUrl).catch((error) => {
      logWarn("Failed to open external URL: " + toErrorMessage(error));
    });
    return { action: "deny" };
  });

  mainWindow.on("closed", () => {
    mainWindow = null;
  });
}

function assertSupportedTopology() {
  if (UNSUPPORTED_TOPOLOGY_MESSAGE) {
    throw new Error(UNSUPPORTED_TOPOLOGY_MESSAGE);
  }
}

function installPermissionGuards() {
  const defaultSession = session.defaultSession;

  defaultSession.setPermissionRequestHandler((_webContents, permission, callback) => {
    logWarn("Denied permission request: " + permission);
    callback(false);
  });

  if (typeof defaultSession.setPermissionCheckHandler === "function") {
    defaultSession.setPermissionCheckHandler(() => false);
  }
}

function corsOriginFromDetails(details) {
  return (
    parseLoopbackOrigin(details.initiator) ||
    parseLoopbackOrigin(details.referrer) ||
    activeRendererOrigin
  );
}

function setupApiInterceptor(actualBackendPort) {
  const devBackendOrigin = "http://localhost:" + PREFERRED_API_PORT;
  const actualBackendOrigin = "http://127.0.0.1:" + actualBackendPort;
  const backendOrigins = [...new Set([devBackendOrigin, actualBackendOrigin])];

  if (PREFERRED_API_PORT !== actualBackendPort) {
    const filter = { urls: [devBackendOrigin + "/*"] };
    session.defaultSession.webRequest.onBeforeRequest(filter, (details, callback) => {
      const redirectURL = details.url.replace(devBackendOrigin, actualBackendOrigin);
      logInfo("Redirecting " + details.url + " → " + redirectURL);
      callback({ redirectURL });
    });
  }

  // Fix CORS — allow the page origin through on all backend responses.
  // This handles the localhost vs 127.0.0.1 mismatch that blocks
  // cross-origin requests from the Electron renderer.
  const corsFilter = { urls: backendOrigins.map((origin) => origin + "/*") };
  session.defaultSession.webRequest.onHeadersReceived(corsFilter, (details, callback) => {
    const headers = { ...details.responseHeaders };
    const corsOrigin = corsOriginFromDetails(details);
    if (corsOrigin) {
      setHeaderValue(headers, "access-control-allow-origin", [corsOrigin]);
      setHeaderValue(headers, "vary", mergeVaryHeader(headers["vary"], "Origin"));
      setHeaderValue(
        headers,
        "access-control-allow-methods",
        ["GET, POST, PUT, DELETE, PATCH, OPTIONS"],
      );
      setHeaderValue(headers, "access-control-allow-headers", [
        "Content-Type, Authorization, X-Requested-With, Accept, trpc-accept, x-trpc-source",
      ]);
    }
    callback({ responseHeaders: headers });
  });

  logInfo("API interceptor active: " + devBackendOrigin + " → " + actualBackendOrigin);
}

async function resolveLoadUrl() {
  if (TOPOLOGY === "next-standalone-runtime") {
    if (isDev) {
      await waitForServerReady({
        label: "Next.js dev server",
        port: PREFERRED_FRONTEND_PORT,
        timeoutMs: 30000,
        preferredHealthPath: "/",
      });
      return "http://127.0.0.1:" + PREFERRED_FRONTEND_PORT;
    }

    const nextPort = await startNextStandaloneServer(PREFERRED_FRONTEND_PORT);
    return "http://127.0.0.1:" + nextPort;
  }

  if (TOPOLOGY === "backend-serves-frontend") {
    if (isDev) {
      setupApiInterceptor(PREFERRED_API_PORT);
      await waitForServerReady({
        label: "Frontend dev server",
        port: PREFERRED_FRONTEND_PORT,
        timeoutMs: 30000,
        preferredHealthPath: "/",
      });
      return "http://127.0.0.1:" + PREFERRED_FRONTEND_PORT;
    }

    const backendPort = await startBundledBackend(PREFERRED_API_PORT);
    setupApiInterceptor(backendPort);
    await ensureBackendServesFrontend(backendPort);
    return "http://127.0.0.1:" + backendPort;
  }

  if (TOPOLOGY === "frontend-static-separate") {
    if (isDev) {
      setupApiInterceptor(PREFERRED_API_PORT);
      await waitForServerReady({
        label: "Frontend dev server",
        port: PREFERRED_FRONTEND_PORT,
        timeoutMs: 30000,
        preferredHealthPath: "/",
      });
      return "http://127.0.0.1:" + PREFERRED_FRONTEND_PORT;
    }

    const backendPort = await startBundledBackend(PREFERRED_API_PORT);
    setupApiInterceptor(backendPort);
    const frontendPort = await startStaticServer(PREFERRED_FRONTEND_PORT, backendPort);
    return "http://127.0.0.1:" + frontendPort;
  }

  if (TOPOLOGY === "frontend-only-static") {
    if (isDev) {
      await waitForServerReady({
        label: "Frontend dev server",
        port: PREFERRED_FRONTEND_PORT,
        timeoutMs: 30000,
        preferredHealthPath: "/",
      });
      return "http://127.0.0.1:" + PREFERRED_FRONTEND_PORT;
    }

    const frontendPort = await startStaticServer(PREFERRED_FRONTEND_PORT, 0);
    return "http://127.0.0.1:" + frontendPort;
  }

  throw new Error("Unsupported topology: " + TOPOLOGY);
}

app.on("second-instance", () => {
  if (!mainWindow) return;
  if (mainWindow.isMinimized()) mainWindow.restore();
  mainWindow.focus();
});

app.whenReady().then(async () => {
  if (startupStarted) return;
  startupStarted = true;

  try {
    assertSupportedTopology();
    installPermissionGuards();
    const loadUrl = await resolveLoadUrl();
    createWindow(loadUrl);
  } catch (error) {
    showStartupError("Failed to start the application.\\n\\n" + toErrorMessage(error));
  }

  app.on("activate", () => {
    if (startupFailed || !activeLoadUrl) return;
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow(activeLoadUrl);
    }
  });
});

app.on("before-quit", () => {
  isQuitting = true;

  if (apiProcess) {
    apiProcess.kill();
    apiProcess = null;
  }
  if (staticServer) {
    staticServer.close();
    staticServer = null;
  }
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});
`.trimStart();
}

function toTitleCase(value: string): string {
  return value
    .replace(/[-_]/g, " ")
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

function normalizeHealthPath(value: string | undefined): string {
  if (!value || value.trim().length === 0) {
    return "/";
  }
  return value.startsWith("/") ? value : `/${value}`;
}

function unsupportedTopologyMessage(topology: DeskpackConfig["topology"]): string | null {
  if (topology === "ssr-framework") {
    return (
      "This SSR/server runtime project is not supported yet. " +
      "For Next.js, use output: 'standalone' or output: 'export' and re-run deskpack init."
    );
  }

  if (topology === "unsupported") {
    return (
      "Deskpack could not determine a supported frontend/backend topology. " +
      "Ensure your backend serves static frontend files or that your frontend can be built as static output."
    );
  }

  return null;
}
